schema = 1

[[sources]]
id = "governor"
label = "Cyan Skillfish governor"
repository = "filippor/cyan-skillfish-governor"
version = "0.4.11"
commit = "60ab6e5b354f01f287c73d920990dcd618a674cc"
url = "https://github.com/filippor/cyan-skillfish-governor/archive/{commit}.tar.gz"
archive = "cyan-skillfish-governor-{commit}.tar.gz"
cargo_vendor = true
vendor_archive = "cyan-skillfish-governor-vendor-{commit}.tar.xz"

[[sources]]
id = "unlock"
label = "40-CU unlock tools"
repository = "fduraibi/bc250-40cu-unlock"
commit = "6c3969ddee40e894297869e6ca30537f274619cb"
url = "https://github.com/fduraibi/bc250-40cu-unlock/archive/{commit}.tar.gz"
archive = "bc250-40cu-unlock-{commit}.tar.gz"

[[sources]]
id = "live_manager"
label = "CU live manager"
repository = "WinnieLV/bc250-cu-live-manager"
commit = "8eb45f07810af738f3e4945ea0cc29d399e378a6"
url = "https://github.com/WinnieLV/bc250-cu-live-manager/archive/{commit}.tar.gz"
archive = "bc250-cu-live-manager-{commit}.tar.gz"
